### ISSUE TITLE
keeru9.com

### ISSUE THREAD

**Issue by keeru9games** [defold/games-showcase#14]
```json
{
    "name": "",
	"description": "",
    "url": "",
    "developer": "",
    "publisher": "",
    "releasedate": "",
    "platforms": "iOS,Android,macOS,Windows,Linux,HTML5,Steam,Poki,itch.io,Kongregate,Facebook Instant Games,...",
    "images": {
        "full": "",
        "half": "",
        "third": ""
    }
}
```

* `name` - (REQUIRED) Name of the awesome Defold game.
* `description` - (REQUIRED) Short text describing the game.
* `url` - (REQUIRED) Link to a game or store page.
* `developer` - (REQUIRED) Name of the developer/studio.
* `publisher` - (OPTIONAL) Name of the publisher.
* `release_date` - (REQUIRED) Date of release (Month Year, eg April 2020).
* `platforms` - (REQUIRED) The platforms where the game can be played. Comma separated list.
* `images` - (REQUIRED) Filenames of images that can be used when presenting the asset.
  * `full` - (REQUIRED) Filename of attached image to use as full width image. PNG or JPG. Recommended size is 3000x750. Name: game-name-full.png|jpg
  * `half` - (REQUIRED) Filename of attached image to use as half width image. PNG or JPG. Recommended size is 1200x600 pixels. Name: game-name-half.png|jpg
  * `third` - (REQUIRED) Filename of attached image to use as one third width image. PNG or JPG. Recommended size is 800x600 pixels. Name: game-name-third.png|jpg

Note: We retain the right to not accept a submitted game and we decide if the game goes on the Showcase or Games page

**Comment by keeru9games** [comment]
we want to upload our webgames on your site, please let us know how we can upload it here,

Our web-game site is [Keeru9](https://keeru9.com/)

**Comment by JCash** [comment]
This site is for showcasing (not running) _Defold_ games only.
To add a _Defold_ game, please fill in the required information (as seen in your first comment).
